name: Generate content

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28.0

      - name: Generate posts
        env:
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        run: |
          python scripts/generate_posts.py

      - name: Commit and push generated posts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto-generate posts [skip ci]"
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
